# @package _global_

models:
  decoder:
    _target_: ${decoder_path}.UNet
    in_channels: [32, 48, 136, 384]  # Input layer channel
    strides: [4, 8, 16, 32]           # Input layer scale
    inner_channels: 256               # Hidden layer channel
    output_channels: 64               # output layer channel
    bias: False
