# @package _global_

defaults:
  - /preset/models/decoder/unet_convnext
  - /preset/models/encoder/timm_backbone_convnext
  - /preset/models/head/db_head
  - /preset/models/loss/db_loss
  - _self_

models:
  optimizer:
    _target_: torch.optim.Adam
    lr: 0.001
    weight_decay: 0.0001
  scheduler:
    _target_: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
    T_0: 5
    T_mult: 1
    eta_min: 0.00001
