# @package _global_

models:
  encoder:
    _target_: ${encoder_path}.TimmBackbone
    model_name: 'efficientnet_b3.ra2_in1k'
    select_features: [1, 2, 3, 4]            # Output layer
    pretrained: true
