# @package _global_

models:
  encoder:
    _target_: ${encoder_path}.TimmBackbone
    model_name: 'mobilenetv3_large_100.ra_in1k'
    select_features: [1, 2, 3, 4]            # Output layer
    pretrained: true
